feat: make sidebar fixed on scroll and add tests
raccoongang/frontend-app-learning pull request #21
Opened 2024-03-18 14:49 UTC by ihor-romaniuk

**Description:** 
- make course outline sidebar fixed on scroll and depends on content height
- add test to course-outline sidebar components

2024-03-21 09:07 UTC, ihor-romaniuk commented on src/courseware/course/sidebar/sidebars/course-outline/SidebarUnit.jsx
Add coverage for `const iconType = isLocked ? UNIT_ICON_TYPES.lock : icon;` after merge https://github.com/raccoongang/frontend-app-learning/pull/24

2024-03-21 13:27 UTC, monteri requested changes

2024-03-21 13:27 UTC, monteri commented on src/courseware/course/sidebar/sidebars/course-outline/CourseOutlineTray.test.jsx
> +  it('doesn\'t renders when outline sidebar is disabled', async () => {
```suggestion
  it('doesn\'t render when outline sidebar is disabled', async () => {
```

2024-03-21 13:27 UTC, monteri commented on src/courseware/course/sidebar/sidebars/course-outline/SidebarSection.test.jsx
> +    fireEvent.click(button);
```suggestion
    userEvent.click(button);
```

2024-03-21 13:27 UTC, monteri commented on src/courseware/course/sidebar/sidebars/course-outline/SidebarSection.test.jsx
> +    fireEvent.click(button);
```suggestion
    userEvent.click(button);
```

2024-03-21 13:27 UTC, monteri commented on src/courseware/course/sidebar/sidebars/course-outline/UnitIcon.jsx
> +  }
```suggestion
const defaultIconType = type || UNIT_ICON_TYPES.other;
let Icon = iconMap[defaultIconType];

if (typeof Icon === 'object') {
  const iconName = isCompleted ? 'complete' : 'default';
  Icon = Icon[iconName];
}
```

2024-03-21 14:45 UTC, monteri commented
Also rebase required?

2024-03-25 10:05 UTC, ihor-romaniuk commented on src/courseware/course/sidebar/sidebars/course-outline/CourseOutlineTray.test.jsx
> +  it('doesn\'t renders when outline sidebar is disabled', async () => {
Changed

2024-03-25 10:06 UTC, ihor-romaniuk commented on src/courseware/course/sidebar/sidebars/course-outline/UnitIcon.jsx
> +  }
Changed in previous PR

2024-03-25 10:06 UTC, ihor-romaniuk commented on src/courseware/course/sidebar/sidebars/course-outline/SidebarSection.test.jsx
> +    fireEvent.click(button);
Changed

2024-03-25 10:06 UTC, ihor-romaniuk commented on src/courseware/course/sidebar/sidebars/course-outline/SidebarSection.test.jsx
> +    fireEvent.click(button);
Changed

2024-03-25 13:23 UTC, merged